export const runtime = "nodejs";

import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(req: Request) {
  try {
    const { name, location, comment } = await req.json();

    // 1. Setup Transporter with Gmail specific settings
    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST, // smtp.gmail.com
      port: Number(process.env.EMAIL_PORT), // 587
      secure: false, // TLS
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS, // Your App Password
      },
    });

    // 2. Verify connection configuration before sending
    try {
      await transporter.verify();
    } catch (verifyError) {
      console.error("SMTP Verification Failed:", verifyError);
      throw new Error("SMTP connection could not be established.");
    }

    const iconBase = "https://img.icons8.com/ios-filled/50/3b82f6";
    const icons = {
      chat: `${iconBase}/chat-message-sent.png`,
      map: `${iconBase}/marker.png`,
      user: `${iconBase}/user-male-circle.png`,
    };

    const mailOptions = {
      from: `"SIS Feedback System" <${process.env.EMAIL_USER}>`,
      to: process.env.EMAIL_TO, // This sends it to the CEO email defined in .env
      subject: `🚨 NEW FEEDBACK: ${name} from ${location}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { margin: 0; padding: 0; background-color: #f1f5f9; font-family: 'Helvetica Neue', Arial, sans-serif; }
            .container { max-width: 600px; margin: 40px auto; background: #ffffff; border-radius: 24px; overflow: hidden; box-shadow: 0 10px 40px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; }
            .banner { background-color: #002147; padding: 40px 20px; text-align: center; }
            .banner h1 { margin: 0; color: #ffffff; font-size: 22px; font-weight: 900; letter-spacing: 1px; }
            .badge { display: inline-block; background: #3b82f6; color: white; padding: 5px 15px; border-radius: 30px; font-size: 10px; font-weight: bold; text-transform: uppercase; margin-top: 12px; }
            .body-content { padding: 40px; }
            .data-table { width: 100%; border-bottom: 1px solid #f1f5f9; padding-bottom: 20px; margin-bottom: 25px; }
            .label-text { font-size: 12px; color: #94a3b8; font-weight: bold; text-transform: uppercase; }
            .value-text { font-size: 15px; color: #0f172a; font-weight: 700; padding-bottom: 15px; }
            .message-box { background-color: #f8fafc; border-left: 5px solid #002147; border-radius: 12px; padding: 25px; margin-top: 10px; }
            .quote { color: #334155; font-size: 16px; line-height: 1.6; font-style: italic; margin: 0; }
            .footer { background: #f8fafc; padding: 25px; text-align: center; border-top: 1px solid #f1f5f9; }
            .footer p { font-size: 11px; color: #94a3b8; margin: 0; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="banner">
              <h1>SIS SOLUTIONS</h1>
              <div class="badge">Executive Alert: Feedback</div>
            </div>
            <div class="body-content">
              <table class="data-table">
                <tr>
                  <td class="label-text"><img src="${icons.user}" width="14"> Client Name</td>
                  <td class="label-text"><img src="${icons.map}" width="14"> Location</td>
                </tr>
                <tr>
                  <td class="value-text">${name}</td>
                  <td class="value-text">${location}</td>
                </tr>
              </table>
              <div class="label-text" style="margin-bottom:10px;"><img src="${icons.chat}" width="14"> Message Body</div>
              <div class="message-box">
                <p class="quote">"${comment}"</p>
              </div>
            </div>
            <div class="footer">
              <p>Generated by SIS ICT Intelligence System &copy; ${new Date().getFullYear()}</p>
            </div>
          </div>
        </body>
        </html>
      `,
    };

    await transporter.sendMail(mailOptions);
    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Critical API Error:", error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}